aws_key = "AKIAIOSFODNN7EXAMPLE"

ssh-private_key = "-----BEGIN OPENSSH PRIVATE KEY-----"


secret_key = "EAtVLIW9qoHOvBP2rW5IpzNXt2BQC3UbTWmrprBpaUP8l9lx4OR"


aws_key3 = "AKIAIOSFODNN5EXAMPLO"

aws_key4 = "AKIAIOSFODNN8EXAMPLO"

secret = "thisisaplaintextsecret"

aws_key5 = "AKIAIOSFODNN9EXAMPLO"

aws_key1 = "AKIAIOSFODNN1EXAMPLO"

aws_key2 = "AKIAIOSFODNN2EXAMPLO"

aws_key6 = "AKIAIOSFODNN7EXAMPLO"

aws_key7 = "AKIAIOSFODNN6EXAMPLO"
