on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  
name: Scan code for secrets

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    

    - name: Run code scanner
      run: |
        docker run --rm -v `pwd`:/proj jmramirezo/secrets-finder:sarif --regex --entropy=True file:///proj
      shell: bash
      continue-on-error: true

    - name: Show sarif file
      run: cat output.sarif
      shell: bash
      continue-on-error: false
    # - id: secret_count
    #   run: |
    #     content=`cat output.sarif | jq '.runs[0] .results | length'`
    #     echo "::set-output name=secretCount::$content"
    # - name: Read json
    #   run: |
    #     echo "${{steps.set_var.outputs.outputJson}}"
    #   shell: bash


    - uses: github/codeql-action/upload-sarif@v1
      name: Upload output sarif file
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: output.sarif
        checkout_path: '${{ github.workspace }}'

    
      
      

